# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Connection": "00_core.ipynb",
         "create_connection": "00_core.ipynb",
         "append_df_to_table": "00_core.ipynb",
         "update_table_from_df": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jose-moralez.github.io/postgres_utils/"

git_url = "https://github.com/jose-moralez/postgres_utils/tree/master/"

def custom_doc_links(name): return None
